services:
  - type: web
    name: cyberlibrary
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn cyberLibrary.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: DATABASE_URL
        fromDatabase:
          name: cyberlibrary-db
          property: connectionString

databases:
  - name: cyberlibrary-db
    databaseName: cyberlibrary
    user: cyberlibrary 