# Generated by Django 5.0.2 on 2025-05-04 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('word_count', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('unique_words_count', models.IntegerField(default=0)),
                ('most_common_word', models.CharField(blank=True, max_length=100)),
                ('most_common_word_count', models.IntegerField(default=0)),
                ('average_word_length', models.FloatField(default=0.0)),
                ('longest_words', models.JSONField(default=list)),
                ('frequency_words', models.JSONField(default=dict)),
                ('equal_length_sequences', models.JSONField(default=list)),
            ],
        ),
    ]
